config/routes.rb
Rails.application.routes.draw do

  root "cars#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cars do
    resources :reviews, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :reviews
end

app/models/concerns/review.rb
class Review < ApplicationRecord
  belongs_to :car

  validates :rating, inclusion: { in: [0,1,2,3,4,5], allow_nil: false }, presence: true, numericality: true
  validates :content, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path
  end


  def create
    Car.create(car_params)
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:name, :brand, :year)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :find_car, only: [ :new, :create ]

  def new
    @review = Review.new
  end

  def create
    @review = @car.reviews.build(review_params)
    @review.save
    redirect_to cars_path
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def find_car
    @car = Car.find(params[:car_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/reviews_controller_helper.rb
module ReviewsControllerHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cars/index.html.erb
<h1 class="text-center">List of cars</h1>

<div class="container">
  <div class="row">
    <% @cars.each do |car| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://static.pexels.com/photos/24353/pexels-photo.jpg');">
        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2><%= car.name %></h2>
          <p><%= car.brand %> - <%= car.year%></p>
        </div>
        <%= link_to "", car_path(car), class: "card-link" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/cars/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Add a new car</h1>
      <%= simple_form_for(@car) do |f| %>
        <%= f.input :name %>
        <%= f.input :brand %>
        <%= f.input :year %>
        <%= f.submit "Create car", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://static.pexels.com/photos/24353/pexels-photo.jpg');">
  <div class="banner-content">
    <h1><%= @car.name %></h1>
    <p><%= @car.brand %> (<%= @car.year %>) </p>
    <a class="btn btn-primary btn-lg">GET IT</a>
  </div>
</div>


<div class="container">
  <% @car.reviews.each do |review|%>

    <div class="review">
      <h2><%= review.content %></h2>
      <p><%= review.rating %> stars</p>
    </div>

  <% end %>
</div>



<%= link_to "Back to list of cars", cars_path %>
<%=link_to "Delete car", car_path(@car), method: :delete %>
<%= link_to "Leave review", new_car_review_path(@car) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>CarRating</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render "shared/navbar" %>
  <%= yield %>
</body>
</html>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1 class="text-center">Add review for <%= @car.name%></h1>
      <%= simple_form_for [@car, @review] do |f| %>
        <%= f.input :content %>
        <%= f.input :rating %>
        <%= f.submit "Create review", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Notification -->
    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Add Car"), new_car_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>